from qutip import *
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as sci
import time

'''https://doi.org/10.1103/PhysRevA.106.L010201'''

## Define parameters
j = 20 # total spin
N = 2*j + 1 # number of particles considering j = j_MAX

p = 0.0

# define the Liouvillian superoperator L
# a is parametr of interaction strength in Hamiltonian
# parameters C, C0, p are related to the dissipation
def L(j, p, h = 1.0, C = 1.0, C0 = 0.0, a = 0.2):
    K1z = spre(jmat(j, 'z'))
    K1x = spre(jmat(j, 'x'))
    K1p = spre(jmat(j, '+'))
    K1m = spre(jmat(j, '-'))

    K2z = spost(jmat(j, 'z').dag())
    K2x = spost(jmat(j, 'x').dag())
    K2p = spost(jmat(j, '+').dag())
    K2m = spost(jmat(j, '-').dag())

    Kzm = K1z - K2z
    Kzp = K1z + K2z
    Kz = K1z * K2z
    Kp = K1p * K2p
    Km = K1m * K2m
    return - C * (j + 1) - 1j * h * Kzm + 1j * a / j * (K1x**2 - K2x**2) + C / j * Kz + (C - C0) * 0.5 / j * Kzm**2 - C * 0.5 * p / j * Kzp + C * (1 - p) * 0.5 / j * Kp + C * (1 + p) * 0.5 / j * Km
# care about the type of object it returns. it should be a superoperator

## Compute and visualize the spectrum of the Liouvillian
#evals = L(j,p).eigenenergies()

# defining an operator Km = K1z - K2z to find the block structure of the Liouvillian as [L, Km] = 0
def Km(j):
    K1z = spre(jmat(j, 'z'))
    K2z = spost(jmat(j, 'z').dag())
    return K1z - K2z

# operator K^2 = K_1^2 * K_2^2 or tensor product of J^2 and (J^2)^T
# this operator is a strong symmetry because J^2 on Hilbert space commutes with H and all L_i
def Ksq(j):
    J2x = jmat(j, 'x')**2
    J2y = jmat(j, 'y')**2
    J2z = jmat(j, 'z')**2
    J2 = J2x + J2y + J2z
    Ksq1 = spre(J2)
    Ksq2 = spost(J2.dag())
    return Ksq1 * Ksq2

# operator K^2+ = K_1^2 + K_2^2
# this operator is a weak symmetry
# eigenvalues should go from 0,..., j^2
# propably a good candidate to find the block structure of the Liouvillian
def Ksqp(j):
    J2x = jmat(j, 'x')**2
    J2y = jmat(j, 'y')**2
    J2z = jmat(j, 'z')**2
    J2 = J2x + J2y + J2z
    Ksq1 = spre(J2)
    Ksq2 = spost(J2.dag())
    return Ksq1 + Ksq2

#print(L(j,p))
#print(Ksq(j))
#print(Ksqp(j))

# diagonalize operator L in blocks given by the eigenvalues of operator K assuming [L,K] = 0, not very general yet
# should add something that finds the sizes of the blocks for general K
def block_eigvals(L, K):
    evalsK, eigvecsK = K.eigenstates()
    L_M = L.transform(eigvecsK) # matrix representation of L in the basis of eigenvectors of K
    L_M = L_M.full() # convert to numpy array

    evals = [] # array to store the eigenvalues of L

    # finding the sizes of the blocks by couting the unique eigenvalues of K
    rounded_evalsK = np.round(evalsK, decimals=5) # round to avoid numerical issues with very close eigenvalues
    _, block_sizes = np.unique(rounded_evalsK, return_counts=True) # 2nd argument returns the counts of each unique value
    #print(block_sizes)
    
    # loop to find the eigenvalues of each block
    n = 0
    for size in block_sizes:
        block = L_M[n:n+size, n:n+size]
        evals_block = sci.eigvals(block)
        evals.append(evals_block)
        n += size

    return np.concatenate(evals)

start = time.time()
evals = block_eigvals(L(j,p), Km(j))
#evals = L(j,p).eigenenergies()
end = time.time()
print("Time taken to compute the spectrum: ", end - start)

plt.scatter(evals.real / j, evals.imag / j, color='black', s=4)
plt.xlabel('Real Part')
plt.ylabel('Imaginary Part')
plt.title('Spectrum of the Liouvillian')
plt.show()

## Separating spectrum into exceptional and normal points to see the Liouvillian spectral phase transition (LSPT)
def spec_separation(evals, threshold): # the threshold should decrease with the system size
    excvals = np.array([])
    normvals = np.array([])

    for a in evals:
        normal = True
        i = 0
        while normal == True and i < len(evals):
            if abs(a - evals[i]) < threshold and a != evals[i]:
                normal = False
            i += 1
        if normal:  
            normvals = np.append(normvals, a)
        else:
            excvals = np.append(excvals, a)
    
    return excvals, normvals

excvals, normvals = spec_separation(evals, 5*1e-2)

#print(expvals)
#print(normvals)

plt.scatter(excvals.real / j, excvals.imag / j, color='red', s=4)
plt.scatter(normvals.real / j, normvals.imag / j, color='blue', s=4)
plt.xlabel('Real Part')
plt.ylabel('Imaginary Part')
plt.title('Spectrum of the Liouvillian with the LSPT')
plt.show()


## Spectrum for M = 0 sector and different values of p

# function that finds a projection of an operator O onto a subspace generated by vecs
# NOTE: does not work with '.proj', most likely because '.eigenstates' does not return 'ket' or 'bra' objects for superoperators
def operator_proj(O, vecs):
    if not vecs:
        return 0 * O
    P = sum([v * v.dag() for v in vecs])
    return P * O * P.dag()


ps = np.linspace(0, 1, 20)

# Lists to collect our coordinates for plotting
all_x = []
all_y = []

'''for p in ps:
    eigvals = operator_proj(L(j,p), [eigvecsM[i] for i in Mzero]).eigenenergies()
    
    x_vals = eigvals.real / j
    y_vals = np.full_like(x_vals, p)
    all_x.extend(x_vals)
    all_y.extend(y_vals)

plt.plot(all_x, all_y, 'k.', markersize=2)
plt.ylabel('p', fontsize=14)
plt.xlabel('Real part of eigenvalues', fontsize=14)
plt.show()'''
# NOTE: does seem good, but some points in the plot seems to be closer comparing with the paper


## Spectrum for M = 0 sector and different values of p with separation of normal and exceptional points
norm_x, norm_y = [], []
exc_x, exc_y = [], []

'''for p in ps:
    eigvals = operator_proj(L(j,p), [eigvecsM[i] for i in Mzero]).eigenenergies()
    
    eigexc, eignorm = spec_separation(eigvals, 0.1)

    n_x_vals = eignorm.real / j
    n_y_vals = np.full_like(n_x_vals, p)
    norm_x.extend(n_x_vals)
    norm_y.extend(n_y_vals)

    e_x_vals = eigexc.real / j
    e_y_vals = np.full_like(e_x_vals, p)
    exc_x.extend(e_x_vals)
    exc_y.extend(e_y_vals)

plt.plot(norm_x, norm_y, 'b.', markersize=2, label='Normal')
plt.plot(exc_x, exc_y, 'r.', markersize=2, label='Exceptional')
plt.ylabel('p', fontsize=14)
plt.xlabel('Real part of eigenvalues', fontsize=14)
plt.legend(loc='best')
plt.show()'''
# NOTE: need to adjust the threshold for separation