from qutip import *
import numpy as np
import matplotlib.pyplot as plt

'''https://doi.org/10.1103/PhysRevA.106.L010201'''

## Define parameters
j = 20 # total spin
N = 2*j + 1 # number of particles considering j = j_MAX

p = 0.99

def L(j, p, h = 1.0, C = 1.0, C0 = 0.0):
    K1z = spre(jmat(j, 'z'))
    K1p = spre(jmat(j, '+'))
    K1m = spre(jmat(j, '-'))

    K2z = spost(jmat(j, 'z').dag())
    K2p = spost(jmat(j, '+').dag())
    K2m = spost(jmat(j, '-').dag())

    Kzm = K1z - K2z
    Kzp = K1z + K2z
    Kz = K1z * K2z
    Kp = K1p * K2p
    Km = K1m * K2m
    return - C * (j + 1) + 1j * h * Kzm + C / j * Kz + (C - C0) * 0.5 / j * Kzm**2 - C * 0.5 * p / j * Kzp + C * (1 - p) * 0.5 / j * Kp + C * (1 + p) * 0.5 / j * Km

## Compute and visualize the spectrum of the Liouvillian
evals = L(j,p).eigenenergies()

'''plt.scatter(evals.real / j, evals.imag / j, color='black', s=4)
plt.xlabel('Real Part')
plt.ylabel('Imaginary Part')
plt.title('Spectrum of the Liouvillian')
plt.show()'''

## Separating spectrum into exceptional and normal points to see the Liouvillian spectral phase transition (LSPT)
def spec_separation(evals, threshold = 1e-1): # the threshold should decrease with the system size
    excvals = np.array([])
    normvals = np.array([])

    for a in evals:
        normal = True
        i = 0
        while normal == True and i < len(evals):
            if abs(a - evals[i]) < threshold and a != evals[i]:
                normal = False
            i += 1
        if normal:
            normvals = np.append(normvals, a)
        else:
            excvals = np.append(excvals, a)
    
    return excvals, normvals

excvals, normvals = spec_separation(evals)

#print(expvals)
#print(normvals)

'''plt.scatter(excvals.real / j, excvals.imag / j, color='red', s=4)
plt.scatter(normvals.real / j, normvals.imag / j, color='blue', s=4)
plt.xlabel('Real Part')
plt.ylabel('Imaginary Part')
plt.title('Spectrum of the Liouvillian with the LSPT')
plt.show()'''


## Spectrum for M = 0 sector and different values of p
def Km(j):
    K1z = spre(jmat(j, 'z'))
    K2z = spost(jmat(j, 'z').dag())
    return K1z - K2z

# diagonalize the Km operator
Ms, eigvecsM = Km(j).eigenstates()
Mzero = np.where(np.isclose(Ms, 0, atol = 1e-8))[0]
#print(Ms)
#print(Mzero)

# function that finds a projection of an operator O onto a subspace generated by vecs
# NOTE: does not work with '.proj', most likely because '.eigenstates' does not return 'ket' or 'bra' objects for superoperators
def operator_proj(O, vecs):
    if not vecs:
        return 0 * O
    P = sum([v * v.dag() for v in vecs])
    return P * O * P.dag()

ps = np.linspace(0, 1, 20)

# Lists to collect our coordinates for plotting
all_x = []
all_y = []

for p in ps:
    eigvals = operator_proj(L(j,p), [eigvecsM[i] for i in Mzero]).eigenenergies()
    
    x_vals = eigvals.real / j
    y_vals = np.full_like(x_vals, p)
    all_x.extend(x_vals)
    all_y.extend(y_vals)

plt.plot(all_x, all_y, 'k.', markersize=2)
plt.ylabel('p', fontsize=14)
plt.xlabel('Real part of eigenvalues', fontsize=14)
plt.show()


## Spectrum for M = 0 sector and different values of p with separation of normal and exceptional points
norm_x, norm_y = [], []
exc_x, exc_y = [], []

for p in ps:
    eigvals = operator_proj(L(j,p), [eigvecsM[i] for i in Mzero]).eigenenergies()
    
    eigexc, eignorm = spec_separation(eigvals)

    n_x_vals = eignorm.real / j
    n_y_vals = np.full_like(n_x_vals, p)
    norm_x.extend(n_x_vals)
    norm_y.extend(n_y_vals)

    e_x_vals = eigexc.real / j
    e_y_vals = np.full_like(e_x_vals, p)
    exc_x.extend(e_x_vals)
    exc_y.extend(e_y_vals)

plt.plot(norm_x, norm_y, 'b.', markersize=2, label='Normal')
plt.plot(exc_x, exc_y, 'r.', markersize=2, label='Exceptional')
plt.ylabel('p', fontsize=14)
plt.xlabel('Real part of eigenvalues', fontsize=14)
plt.legend(loc='best')
plt.show()